ALTER TABLE `Course`
  MODIFY `level` ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ALL_LEVELS') NOT NULL DEFAULT 'BEGINNER',
  MODIFY `status` ENUM('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED', 'UNPUBLISHED') NOT NULL DEFAULT 'DRAFT',
  ADD COLUMN `subtitle` TEXT NULL,
  ADD COLUMN `featured` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `learningOutcomes` JSON NULL,
  ADD COLUMN `requirements` JSON NULL,
  ADD COLUMN `targetAudience` TEXT NULL,
  ADD COLUMN `tags` JSON NULL,
  ADD COLUMN `promoVideoUrl` TEXT NULL,
  ADD COLUMN `rejectionReason` TEXT NULL,
  ADD COLUMN `submittedAt` DATETIME(3) NULL,
  ADD COLUMN `publishedAt` DATETIME(3) NULL;
